"""Web-platform domain contracts that do not depend on persistence or runtime OCR."""

from court_ocr_extract.domain.field_status import (
    FieldMissingReason,
    FieldValue,
    FieldValueStatus,
    FieldValueValidationError,
    is_publishable_field_status,
    is_resolved_field_status,
)
from court_ocr_extract.domain.form_engine import (
    CapabilityStatus,
    ExclusionRule,
    FormCatalog,
    FormCatalogEntry,
    FormDefinition,
    FormEngineCapabilities,
    FormFieldDefinition,
    FormFieldMapping,
    FormGenerationRequest,
    FormTemplate,
    FormTemplateVersion,
    Formatter,
    GenerationMode,
    GenerationRequest,
    GenerationResult,
    GenerationSource,
    GeneratedDocument,
    ManualField,
    Result,
    SourceResolver,
    SourceType,
    TemplateAdapter,
    TemplateFormat,
    get_form_engine_capabilities,
)
from court_ocr_extract.domain.schema_contract import (
    CRIMINAL_FINAL_EXCEL_SCHEMA,
    SchemaColumn,
    SchemaContract,
    get_final_excel_schema_contract,
    get_schema_contract,
)
from court_ocr_extract.domain.workflow import (
    VALID_TRANSITIONS,
    InvalidWorkflowTransition,
    WorkflowState,
    WorkflowTransition,
    WorkflowTransitionValidator,
)

__all__ = [
    "CRIMINAL_FINAL_EXCEL_SCHEMA",
    "CapabilityStatus",
    "ExclusionRule",
    "FINAL_EXCEL_SCHEMA",
    "FieldMissingReason",
    "FieldValue",
    "FieldValueStatus",
    "FieldValueValidationError",
    "FormCatalog",
    "FormCatalogEntry",
    "FormDefinition",
    "FormEngineCapabilities",
    "FormFieldDefinition",
    "FormFieldMapping",
    "FormGenerationRequest",
    "FormTemplate",
    "FormTemplateVersion",
    "Formatter",
    "GenerationMode",
    "GenerationRequest",
    "GenerationResult",
    "GenerationSource",
    "GeneratedDocument",
    "InvalidWorkflowTransition",
    "ManualField",
    "Result",
    "SchemaColumn",
    "SchemaContract",
    "SourceResolver",
    "SourceType",
    "TemplateAdapter",
    "TemplateFormat",
    "VALID_TRANSITIONS",
    "WorkflowState",
    "WorkflowTransition",
    "WorkflowTransitionValidator",
    "get_final_excel_schema_contract",
    "get_form_engine_capabilities",
    "get_schema_contract",
    "is_publishable_field_status",
    "is_resolved_field_status",
]

# Compatibility-friendly name for callers that do not need the domain prefix.
FINAL_EXCEL_SCHEMA = CRIMINAL_FINAL_EXCEL_SCHEMA
