"""Create the reviewed Phase 0 model tables.

Revision ID: 0002_phase0_tables
Revises: 0001_phase0_foundation
Create Date: 2026-07-24
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_phase0_tables'
down_revision: str | Sequence[str] | None = '0001_phase0_foundation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_role',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("code IN ('operator', 'reviewer', 'approver', 'project_admin', 'system_admin')", name=op.f('ck_audit_access_role_')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_access_role')),
    sa.UniqueConstraint('code', name=op.f('uq_audit_access_role_code')),
    schema='audit'
    )
    op.create_index('ix_audit_access_role_status', 'access_role', ['status'], unique=False, schema='audit')
    op.create_table('app_user',
    sa.Column('subject_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_app_user')),
    sa.UniqueConstraint('subject_key', name=op.f('uq_audit_app_user_subject_key')),
    schema='audit'
    )
    op.create_index('ix_audit_app_user_status', 'app_user', ['status'], unique=False, schema='audit')
    op.create_table('form_catalog_entry',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_domain', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms_form_catalog_entry')),
    sa.UniqueConstraint('code', name=op.f('uq_forms_form_catalog_entry_code')),
    schema='forms'
    )
    op.create_index('ix_forms_form_catalog_entry_domain_status', 'form_catalog_entry', ['case_domain', 'status'], unique=False, schema='forms')
    op.create_table('app_user_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['audit.app_user.id'], name=op.f('fk_audit_app_user_role_granted_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['audit.access_role.id'], name=op.f('fk_audit_app_user_role_role_id_access_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['audit.app_user.id'], name=op.f('fk_audit_app_user_role_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_app_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_audit_app_user_role_user_id')),
    schema='audit'
    )
    op.create_index('ix_audit_app_user_role_role_status', 'app_user_role', ['role_id', 'status'], unique=False, schema='audit')
    op.create_index('ix_audit_app_user_role_user_status', 'app_user_role', ['user_id', 'status'], unique=False, schema='audit')
    op.create_table('audit_event',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('subject_type', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=120), nullable=True),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['audit.app_user.id'], name=op.f('fk_audit_audit_event_actor_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_audit_event')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_audit_event_actor_user_id'), 'audit_event', ['actor_user_id'], unique=False, schema='audit')
    op.create_index('ix_audit_audit_event_correlation', 'audit_event', ['correlation_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_audit_event_event_type'), 'audit_event', ['event_type'], unique=False, schema='audit')
    op.create_index('ix_audit_audit_event_subject', 'audit_event', ['subject_type', 'subject_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_audit_event_subject_id'), 'audit_event', ['subject_id'], unique=False, schema='audit')
    op.create_table('form_template',
    sa.Column('catalog_entry_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_entry_id'], ['forms.form_catalog_entry.id'], name=op.f('fk_forms_form_template_catalog_entry_id_form_catalog_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms_form_template')),
    sa.UniqueConstraint('catalog_entry_id', 'name', name=op.f('uq_forms_form_template_catalog_entry_id')),
    schema='forms'
    )
    op.create_index(op.f('ix_forms_form_template_catalog_entry_id'), 'form_template', ['catalog_entry_id'], unique=False, schema='forms')
    op.create_table('job',
    sa.Column('request_key', sa.String(length=255), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('source_kind', sa.String(length=50), nullable=False),
    sa.Column('case_domain', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['audit.app_user.id'], name=op.f('fk_ingest_job_requested_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_job')),
    sa.UniqueConstraint('request_key', name=op.f('uq_ingest_job_request_key')),
    schema='ingest'
    )
    op.create_index('ix_ingest_job_requested_by_created_at', 'job', ['requested_by_user_id', 'created_at'], unique=False, schema='ingest')
    op.create_index('ix_ingest_job_status_created_at', 'job', ['status', 'created_at'], unique=False, schema='ingest')
    op.create_table('review_task',
    sa.Column('task_key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['audit.app_user.id'], name=op.f('fk_review_review_task_assigned_to_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['audit.app_user.id'], name=op.f('fk_review_review_task_created_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_review_task')),
    sa.UniqueConstraint('task_key', name='uq_review_review_task_task_key'),
    schema='review'
    )
    op.create_index('ix_review_review_task_assignee_status', 'review_task', ['assigned_to_user_id', 'status'], unique=False, schema='review')
    op.create_index('ix_review_review_task_status_priority', 'review_task', ['status', 'priority'], unique=False, schema='review')
    op.create_table('document',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('document_key', sa.String(length=255), nullable=False),
    sa.Column('document_kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version_number', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingest.job.id'], name=op.f('fk_ingest_document_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_document')),
    sa.UniqueConstraint('job_id', 'document_key', name=op.f('uq_ingest_document_job_id')),
    schema='ingest'
    )
    op.create_index('ix_ingest_document_job_status', 'document', ['job_id', 'status'], unique=False, schema='ingest')
    op.create_index('ix_ingest_document_status_created_at', 'document', ['status', 'created_at'], unique=False, schema='ingest')
    op.create_table('artifact',
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('retention_state', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['audit.app_user.id'], name=op.f('fk_ingest_artifact_created_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['ingest.document.id'], name=op.f('fk_ingest_artifact_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ingest.job.id'], name=op.f('fk_ingest_artifact_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_artifact')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_ingest_artifact_storage_key')),
    schema='ingest'
    )
    op.create_index('ix_ingest_artifact_checksum', 'artifact', ['checksum_sha256'], unique=False, schema='ingest')
    op.create_index('ix_ingest_artifact_job_document', 'artifact', ['job_id', 'document_id'], unique=False, schema='ingest')
    op.create_index('ix_ingest_artifact_type_created_at', 'artifact', ['artifact_type', 'created_at'], unique=False, schema='ingest')
    op.create_table('form_template_version',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('template_format', sa.String(length=32), nullable=False),
    sa.Column('adapter_type', sa.String(length=32), nullable=False),
    sa.Column('adapter_status', sa.String(length=32), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("adapter_status IN ('NOT_IMPLEMENTED', 'DECLARED', 'AVAILABLE', 'UNAVAILABLE')", name='ck_forms_form_template_version_adapter_status'),
    sa.ForeignKeyConstraint(['artifact_id'], ['ingest.artifact.id'], name=op.f('fk_forms_form_template_version_artifact_id_artifact')),
    sa.ForeignKeyConstraint(['template_id'], ['forms.form_template.id'], name=op.f('fk_forms_form_template_version_template_id_form_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms_form_template_version')),
    sa.UniqueConstraint('template_id', 'version', name=op.f('uq_forms_form_template_version_template_id')),
    schema='forms'
    )
    op.create_index(op.f('ix_forms_form_template_version_artifact_id'), 'form_template_version', ['artifact_id'], unique=False, schema='forms')
    op.create_index(op.f('ix_forms_form_template_version_template_id'), 'form_template_version', ['template_id'], unique=False, schema='forms')
    op.create_table('document_version',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('supersedes_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ingest.document.id'], name=op.f('fk_ingest_document_version_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['ingest.artifact.id'], name=op.f('fk_ingest_document_version_source_artifact_id_artifact'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_version_id'], ['ingest.document_version.id'], name=op.f('fk_ingest_document_version_supersedes_version_id_document_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_document_version')),
    sa.UniqueConstraint('document_id', 'version_number', name=op.f('uq_ingest_document_version_document_id')),
    sa.UniqueConstraint('source_artifact_id', name=op.f('uq_ingest_document_version_source_artifact_id')),
    schema='ingest'
    )
    op.create_index('ix_ingest_document_version_document_status', 'document_version', ['document_id', 'status'], unique=False, schema='ingest')
    op.create_table('form_definition',
    sa.Column('catalog_entry_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('definition_key', sa.String(length=120), nullable=False),
    sa.Column('schema_id', sa.String(length=120), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_entry_id'], ['forms.form_catalog_entry.id'], name=op.f('fk_forms_form_definition_catalog_entry_id_form_catalog_entry')),
    sa.ForeignKeyConstraint(['template_version_id'], ['forms.form_template_version.id'], name=op.f('fk_forms_form_definition_template_version_id_form_template_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms_form_definition')),
    sa.UniqueConstraint('definition_key', 'version', name=op.f('uq_forms_form_definition_definition_key')),
    schema='forms'
    )
    op.create_index(op.f('ix_forms_form_definition_catalog_entry_id'), 'form_definition', ['catalog_entry_id'], unique=False, schema='forms')
    op.create_index(op.f('ix_forms_form_definition_template_version_id'), 'form_definition', ['template_version_id'], unique=False, schema='forms')
    op.create_table('document_page',
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('width_pixels', sa.Integer(), nullable=True),
    sa.Column('height_pixels', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['ingest.document_version.id'], name=op.f('fk_ingest_document_page_document_version_id_document_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_artifact_id'], ['ingest.artifact.id'], name=op.f('fk_ingest_document_page_page_artifact_id_artifact'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_document_page')),
    sa.UniqueConstraint('document_version_id', 'page_number', name=op.f('uq_ingest_document_page_document_version_id')),
    sa.UniqueConstraint('page_artifact_id', name=op.f('uq_ingest_document_page_page_artifact_id')),
    schema='ingest'
    )
    op.create_index('ix_ingest_document_page_version_status', 'document_page', ['document_version_id', 'status'], unique=False, schema='ingest')
    op.create_table('processing_run',
    sa.Column('run_key', sa.String(length=255), nullable=False),
    sa.Column('run_version', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('pipeline_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['ingest.document_version.id'], name=op.f('fk_processing_processing_run_document_version_id_document_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ingest.job.id'], name=op.f('fk_processing_processing_run_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_processing_run')),
    sa.UniqueConstraint('document_version_id', 'run_version', name=op.f('uq_processing_processing_run_document_version_id')),
    sa.UniqueConstraint('run_key', name=op.f('uq_processing_processing_run_run_key')),
    schema='processing'
    )
    op.create_index('ix_processing_run_document_status', 'processing_run', ['document_version_id', 'status'], unique=False, schema='processing')
    op.create_index('ix_processing_run_job_created_at', 'processing_run', ['job_id', 'created_at'], unique=False, schema='processing')
    op.create_index('ix_processing_run_status_created_at', 'processing_run', ['status', 'created_at'], unique=False, schema='processing')
    op.create_table('form_field_definition',
    sa.Column('form_definition_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=40), nullable=False),
    sa.Column('output_placeholder', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('allow_manual_input', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_definition_id'], ['forms.form_definition.id'], name=op.f('fk_forms_form_field_definition_form_definition_id_form_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms_form_field_definition')),
    sa.UniqueConstraint('form_definition_id', 'field_key', name=op.f('uq_forms_form_field_definition_form_definition_id')),
    schema='forms'
    )
    op.create_index(op.f('ix_forms_form_field_definition_form_definition_id'), 'form_field_definition', ['form_definition_id'], unique=False, schema='forms')
    op.create_table('pipeline_step',
    sa.Column('processing_run_id', sa.Uuid(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('step_version', sa.String(length=100), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing.processing_run.id'], name=op.f('fk_processing_pipeline_step_processing_run_id_processing_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_pipeline_step')),
    sa.UniqueConstraint('processing_run_id', 'step_key', 'attempt_number', name=op.f('uq_processing_pipeline_step_processing_run_id')),
    schema='processing'
    )
    op.create_index('ix_processing_pipeline_step_run_status', 'pipeline_step', ['processing_run_id', 'status'], unique=False, schema='processing')
    op.create_index('ix_processing_pipeline_step_status_created_at', 'pipeline_step', ['status', 'created_at'], unique=False, schema='processing')
    op.create_table('form_field_mapping',
    sa.Column('field_definition_id', sa.Uuid(), nullable=False),
    sa.Column('mapping_order', sa.Integer(), nullable=False),
    sa.Column('source_entity', sa.String(length=120), nullable=True),
    sa.Column('source_field', sa.String(length=160), nullable=True),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('transformation', sa.String(length=160), nullable=True),
    sa.Column('formatter', sa.String(length=160), nullable=True),
    sa.Column('default_value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('visibility_condition_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('repeat_rule_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('exclusion_rule_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation_rule_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('instruction_removal_rule_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['forms.form_field_definition.id'], name=op.f('fk_forms_form_field_mapping_field_definition_id_form_field_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms_form_field_mapping')),
    sa.UniqueConstraint('field_definition_id', 'mapping_order', name=op.f('uq_forms_form_field_mapping_field_definition_id')),
    schema='forms'
    )
    op.create_index(op.f('ix_forms_form_field_mapping_field_definition_id'), 'form_field_mapping', ['field_definition_id'], unique=False, schema='forms')
    op.create_table('extraction_snapshot',
    sa.Column('processing_run_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('produced_by_step_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('case_domain', sa.String(length=32), nullable=False),
    sa.Column('is_machine_output', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['ingest.document_version.id'], name=op.f('fk_processing_extraction_snapshot_document_version_id_document_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing.processing_run.id'], name=op.f('fk_processing_extraction_snapshot_processing_run_id_processing_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produced_by_step_id'], ['processing.pipeline_step.id'], name=op.f('fk_processing_extraction_snapshot_produced_by_step_id_pipeline_step'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_extraction_snapshot')),
    sa.UniqueConstraint('processing_run_id', 'snapshot_version', name=op.f('uq_processing_extraction_snapshot_processing_run_id')),
    schema='processing'
    )
    op.create_index('ix_processing_extraction_snapshot_document_created_at', 'extraction_snapshot', ['document_version_id', 'created_at'], unique=False, schema='processing')
    op.create_index('ix_processing_extraction_snapshot_run_status', 'extraction_snapshot', ['processing_run_id', 'status'], unique=False, schema='processing')
    op.create_table('extracted_entity',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_key', sa.String(length=255), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['processing.extraction_snapshot.id'], name=op.f('fk_processing_extracted_entity_snapshot_id_extraction_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_extracted_entity')),
    sa.UniqueConstraint('snapshot_id', 'entity_type', 'ordinal', name=op.f('uq_processing_extracted_entity_snapshot_id')),
    schema='processing'
    )
    op.create_index('ix_processing_extracted_entity_snapshot_status', 'extracted_entity', ['snapshot_id', 'status'], unique=False, schema='processing')
    op.create_table('review_version',
    sa.Column('review_task_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('case_domain', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('supersedes_review_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('review_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['audit.app_user.id'], name=op.f('fk_review_review_version_created_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extraction_snapshot_id'], ['processing.extraction_snapshot.id'], name=op.f('fk_review_review_version_extraction_snapshot_id_extraction_snapshot'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['audit.app_user.id'], name=op.f('fk_review_review_version_locked_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_task_id'], ['review.review_task.id'], name=op.f('fk_review_review_version_review_task_id_review_task'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_review_version_id'], ['review.review_version.id'], name=op.f('fk_review_review_version_supersedes_review_version_id_review_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_review_version')),
    sa.UniqueConstraint('review_task_id', 'version', name='uq_review_review_version_task_version'),
    schema='review'
    )
    op.create_index('ix_review_review_version_extraction_snapshot', 'review_version', ['extraction_snapshot_id'], unique=False, schema='review')
    op.create_index('ix_review_review_version_status_locked', 'review_version', ['status', 'locked'], unique=False, schema='review')
    op.create_index('ix_review_review_version_supersedes', 'review_version', ['supersedes_review_version_id'], unique=False, schema='review')
    op.create_table('extracted_field',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('occurrence', sa.Integer(), nullable=False),
    sa.Column('machine_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('normalized_machine_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('field_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['processing.extracted_entity.id'], name=op.f('fk_processing_extracted_field_entity_id_extracted_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_extracted_field')),
    sa.UniqueConstraint('entity_id', 'field_key', 'occurrence', name=op.f('uq_processing_extracted_field_entity_id')),
    schema='processing'
    )
    op.create_index('ix_processing_extracted_field_entity_status', 'extracted_field', ['entity_id', 'field_status'], unique=False, schema='processing')
    op.create_table('approval',
    sa.Column('review_version_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['audit.app_user.id'], name=op.f('fk_review_approval_approved_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_version_id'], ['review.review_version.id'], name=op.f('fk_review_approval_review_version_id_review_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_approval')),
    sa.UniqueConstraint('review_version_id', name='uq_review_approval_review_version'),
    schema='review'
    )
    op.create_index('ix_review_approval_actor', 'approval', ['approved_by_user_id', 'approved_at'], unique=False, schema='review')
    op.create_index('ix_review_approval_decision', 'approval', ['review_version_id', 'decision'], unique=False, schema='review')
    op.create_table('published_snapshot',
    sa.Column('review_version_id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('case_domain', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['review.approval.id'], name=op.f('fk_core_published_snapshot_approval_id_approval'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_version_id'], ['review.review_version.id'], name=op.f('fk_core_published_snapshot_review_version_id_review_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_published_snapshot')),
    sa.UniqueConstraint('approval_id', name='uq_core_published_snapshot_approval'),
    sa.UniqueConstraint('review_version_id', name='uq_core_published_snapshot_review_version'),
    schema='core'
    )
    op.create_index('ix_core_published_snapshot_status_time', 'published_snapshot', ['status', 'published_at'], unique=False, schema='core')
    op.create_table('evidence_ref',
    sa.Column('extracted_field_id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('locator_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['ingest.artifact.id'], name=op.f('fk_processing_evidence_ref_artifact_id_artifact'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_page_id'], ['ingest.document_page.id'], name=op.f('fk_processing_evidence_ref_document_page_id_document_page'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['processing.extracted_field.id'], name=op.f('fk_processing_evidence_ref_extracted_field_id_extracted_field'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_evidence_ref')),
    sa.UniqueConstraint('extracted_field_id', 'rank', name=op.f('uq_processing_evidence_ref_extracted_field_id')),
    schema='processing'
    )
    op.create_index('ix_processing_evidence_ref_field_status', 'evidence_ref', ['extracted_field_id', 'status'], unique=False, schema='processing')
    op.create_index('ix_processing_evidence_ref_page', 'evidence_ref', ['document_page_id'], unique=False, schema='processing')
    op.create_table('extraction_warning',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('extracted_field_id', sa.Uuid(), nullable=True),
    sa.Column('warning_code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['processing.extracted_field.id'], name=op.f('fk_processing_extraction_warning_extracted_field_id_extracted_field'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['processing.extraction_snapshot.id'], name=op.f('fk_processing_extraction_warning_snapshot_id_extraction_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_extraction_warning')),
    schema='processing'
    )
    op.create_index('ix_processing_extraction_warning_field_status', 'extraction_warning', ['extracted_field_id', 'status'], unique=False, schema='processing')
    op.create_index('ix_processing_extraction_warning_snapshot_severity', 'extraction_warning', ['snapshot_id', 'severity'], unique=False, schema='processing')
    op.create_table('field_review',
    sa.Column('review_version_id', sa.Uuid(), nullable=False),
    sa.Column('extracted_field_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=512), nullable=False),
    sa.Column('machine_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reviewed_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('machine_status', sa.String(length=32), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['processing.extracted_field.id'], name=op.f('fk_review_field_review_extracted_field_id_extracted_field'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_version_id'], ['review.review_version.id'], name=op.f('fk_review_field_review_review_version_id_review_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['audit.app_user.id'], name=op.f('fk_review_field_review_reviewed_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_field_review')),
    sa.UniqueConstraint('review_version_id', 'extracted_field_id', name='uq_review_field_review_version_machine_field'),
    sa.UniqueConstraint('review_version_id', 'field_path', name='uq_review_field_review_version_path'),
    schema='review'
    )
    op.create_index('ix_review_field_review_machine_field', 'field_review', ['extracted_field_id'], unique=False, schema='review')
    op.create_index('ix_review_field_review_reviewer', 'field_review', ['reviewed_by_user_id', 'reviewed_at'], unique=False, schema='review')
    op.create_index('ix_review_field_review_status', 'field_review', ['review_version_id', 'review_status'], unique=False, schema='review')
    op.create_table('court_case',
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=255), nullable=False),
    sa.Column('case_type', sa.String(length=64), nullable=True),
    sa.Column('court_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('adjudicated_on', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_core_court_case_published_snapshot_id_published_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_court_case')),
    sa.UniqueConstraint('published_snapshot_id', 'case_number', name='uq_core_court_case_snapshot_number'),
    schema='core'
    )
    op.create_index('ix_core_court_case_court', 'court_case', ['court_name', 'adjudicated_on'], unique=False, schema='core')
    op.create_index('ix_core_court_case_snapshot_status', 'court_case', ['published_snapshot_id', 'status'], unique=False, schema='core')
    op.create_table('person',
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('person_key', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('identity_document_type', sa.String(length=32), nullable=True),
    sa.Column('identity_document_number', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_core_person_published_snapshot_id_published_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_person')),
    sa.UniqueConstraint('published_snapshot_id', 'person_key', name='uq_core_person_snapshot_key'),
    schema='core'
    )
    op.create_index('ix_core_person_snapshot_name', 'person', ['published_snapshot_id', 'full_name'], unique=False, schema='core')
    op.create_table('source_document_link',
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_start', sa.Integer(), nullable=True),
    sa.Column('source_page_end', sa.Integer(), nullable=True),
    sa.Column('source_locator', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['ingest.document_version.id'], name=op.f('fk_core_source_document_link_document_version_id_document_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_core_source_document_link_published_snapshot_id_published_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_source_document_link')),
    sa.UniqueConstraint('published_snapshot_id', 'document_version_id', 'entity_type', 'entity_id', 'source_page_start', 'source_page_end', name='uq_core_source_document_link_evidence'),
    schema='core'
    )
    op.create_index('ix_core_source_document_link_document', 'source_document_link', ['document_version_id', 'source_page_start'], unique=False, schema='core')
    op.create_index('ix_core_source_document_link_entity', 'source_document_link', ['published_snapshot_id', 'entity_type', 'entity_id'], unique=False, schema='core')
    op.create_table('form_generation_request',
    sa.Column('form_definition_id', sa.Uuid(), nullable=False),
    sa.Column('approved_review_version_id', sa.Uuid(), nullable=True),
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('output_format', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('(approved_review_version_id IS NOT NULL AND published_snapshot_id IS NULL) OR (approved_review_version_id IS NULL AND published_snapshot_id IS NOT NULL)', name='ck_forms_generation_source'),
    sa.ForeignKeyConstraint(['approved_review_version_id'], ['review.review_version.id'], name=op.f('fk_forms_form_generation_request_approved_review_version_id_review_version')),
    sa.ForeignKeyConstraint(['form_definition_id'], ['forms.form_definition.id'], name=op.f('fk_forms_form_generation_request_form_definition_id_form_definition')),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_forms_form_generation_request_published_snapshot_id_published_snapshot')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['audit.app_user.id'], name=op.f('fk_forms_form_generation_request_requested_by_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms_form_generation_request')),
    schema='forms'
    )
    op.create_index(op.f('ix_forms_form_generation_request_approved_review_version_id'), 'form_generation_request', ['approved_review_version_id'], unique=False, schema='forms')
    op.create_index(op.f('ix_forms_form_generation_request_form_definition_id'), 'form_generation_request', ['form_definition_id'], unique=False, schema='forms')
    op.create_index(op.f('ix_forms_form_generation_request_published_snapshot_id'), 'form_generation_request', ['published_snapshot_id'], unique=False, schema='forms')
    op.create_index(op.f('ix_forms_form_generation_request_requested_by_user_id'), 'form_generation_request', ['requested_by_user_id'], unique=False, schema='forms')
    op.create_index('ix_forms_form_generation_request_status', 'form_generation_request', ['status'], unique=False, schema='forms')
    op.create_table('field_correction',
    sa.Column('review_version_id', sa.Uuid(), nullable=False),
    sa.Column('field_review_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('corrected_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('corrected_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['audit.app_user.id'], name=op.f('fk_review_field_correction_corrected_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_review_id'], ['review.field_review.id'], name=op.f('fk_review_field_correction_field_review_id_field_review'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_version_id'], ['review.review_version.id'], name=op.f('fk_review_field_correction_review_version_id_review_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_field_correction')),
    sa.UniqueConstraint('field_review_id', 'version', name='uq_review_field_correction_review_number'),
    schema='review'
    )
    op.create_index('ix_review_field_correction_actor', 'field_correction', ['corrected_by_user_id', 'corrected_at'], unique=False, schema='review')
    op.create_index('ix_review_field_correction_version', 'field_correction', ['review_version_id', 'corrected_at'], unique=False, schema='review')
    op.create_table('review_comment',
    sa.Column('review_version_id', sa.Uuid(), nullable=False),
    sa.Column('field_review_id', sa.Uuid(), nullable=True),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('comment_number', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['audit.app_user.id'], name=op.f('fk_review_review_comment_author_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_review_id'], ['review.field_review.id'], name=op.f('fk_review_review_comment_field_review_id_field_review'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['review.review_comment.id'], name=op.f('fk_review_review_comment_parent_comment_id_review_comment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['audit.app_user.id'], name=op.f('fk_review_review_comment_resolved_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_version_id'], ['review.review_version.id'], name=op.f('fk_review_review_comment_review_version_id_review_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_review_comment')),
    sa.UniqueConstraint('review_version_id', 'comment_number', name='uq_review_review_comment_version_number'),
    schema='review'
    )
    op.create_index('ix_review_review_comment_author', 'review_comment', ['author_user_id', 'created_at'], unique=False, schema='review')
    op.create_index('ix_review_review_comment_field', 'review_comment', ['field_review_id', 'created_at'], unique=False, schema='review')
    op.create_table('address',
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('address_number', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=32), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('ward', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('province', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['core.person.id'], name=op.f('fk_core_address_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_core_address_published_snapshot_id_published_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_address')),
    sa.UniqueConstraint('person_id', 'address_number', name='uq_core_address_person_number'),
    schema='core'
    )
    op.create_index('ix_core_address_admin', 'address', ['province', 'district', 'ward'], unique=False, schema='core')
    op.create_index('ix_core_address_snapshot', 'address', ['published_snapshot_id'], unique=False, schema='core')
    op.create_table('case_party',
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('court_case_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('party_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['court_case_id'], ['core.court_case.id'], name=op.f('fk_core_case_party_court_case_id_court_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['core.person.id'], name=op.f('fk_core_case_party_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_core_case_party_published_snapshot_id_published_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_case_party')),
    sa.UniqueConstraint('court_case_id', 'party_number', name='uq_core_case_party_case_number'),
    schema='core'
    )
    op.create_index('ix_core_case_party_person', 'case_party', ['person_id', 'court_case_id'], unique=False, schema='core')
    op.create_index('ix_core_case_party_snapshot_role', 'case_party', ['published_snapshot_id', 'role'], unique=False, schema='core')
    op.create_table('judgment',
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('court_case_id', sa.Uuid(), nullable=False),
    sa.Column('judgment_number', sa.String(length=255), nullable=False),
    sa.Column('judgment_date', sa.Date(), nullable=True),
    sa.Column('judgment_type', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['court_case_id'], ['core.court_case.id'], name=op.f('fk_core_judgment_court_case_id_court_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_core_judgment_published_snapshot_id_published_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_judgment')),
    sa.UniqueConstraint('published_snapshot_id', 'judgment_number', name='uq_core_judgment_snapshot_number'),
    schema='core'
    )
    op.create_index('ix_core_judgment_case_date', 'judgment', ['court_case_id', 'judgment_date'], unique=False, schema='core')
    op.create_index('ix_core_judgment_snapshot', 'judgment', ['published_snapshot_id'], unique=False, schema='core')
    op.create_table('generated_document',
    sa.Column('generation_request_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('output_format', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['ingest.artifact.id'], name=op.f('fk_forms_generated_document_artifact_id_artifact')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['audit.app_user.id'], name=op.f('fk_forms_generated_document_created_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['generation_request_id'], ['forms.form_generation_request.id'], name=op.f('fk_forms_generated_document_generation_request_id_form_generation_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms_generated_document')),
    sa.UniqueConstraint('generation_request_id', 'version', name=op.f('uq_forms_generated_document_generation_request_id')),
    schema='forms'
    )
    op.create_index(op.f('ix_forms_generated_document_artifact_id'), 'generated_document', ['artifact_id'], unique=False, schema='forms')
    op.create_index(op.f('ix_forms_generated_document_created_by_user_id'), 'generated_document', ['created_by_user_id'], unique=False, schema='forms')
    op.create_index(op.f('ix_forms_generated_document_generation_request_id'), 'generated_document', ['generation_request_id'], unique=False, schema='forms')
    op.create_table('charge',
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('court_case_id', sa.Uuid(), nullable=False),
    sa.Column('case_party_id', sa.Uuid(), nullable=False),
    sa.Column('charge_number', sa.Integer(), nullable=False),
    sa.Column('charge_code', sa.String(length=128), nullable=True),
    sa.Column('charge_name', sa.String(length=512), nullable=True),
    sa.Column('legal_provision', sa.Text(), nullable=True),
    sa.Column('disposition', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_party_id'], ['core.case_party.id'], name=op.f('fk_core_charge_case_party_id_case_party'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['court_case_id'], ['core.court_case.id'], name=op.f('fk_core_charge_court_case_id_court_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_core_charge_published_snapshot_id_published_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_charge')),
    sa.UniqueConstraint('court_case_id', 'charge_number', name='uq_core_charge_case_number'),
    schema='core'
    )
    op.create_index('ix_core_charge_party', 'charge', ['case_party_id', 'disposition'], unique=False, schema='core')
    op.create_index('ix_core_charge_snapshot', 'charge', ['published_snapshot_id'], unique=False, schema='core')
    op.create_table('sentence',
    sa.Column('published_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('judgment_id', sa.Uuid(), nullable=False),
    sa.Column('case_party_id', sa.Uuid(), nullable=False),
    sa.Column('charge_id', sa.Uuid(), nullable=True),
    sa.Column('sentence_number', sa.Integer(), nullable=False),
    sa.Column('sentence_type', sa.String(length=64), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('fine_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_party_id'], ['core.case_party.id'], name=op.f('fk_core_sentence_case_party_id_case_party'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['charge_id'], ['core.charge.id'], name=op.f('fk_core_sentence_charge_id_charge'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['judgment_id'], ['core.judgment.id'], name=op.f('fk_core_sentence_judgment_id_judgment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_snapshot_id'], ['core.published_snapshot.id'], name=op.f('fk_core_sentence_published_snapshot_id_published_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_sentence')),
    sa.UniqueConstraint('judgment_id', 'sentence_number', name='uq_core_sentence_judgment_number'),
    schema='core'
    )
    op.create_index('ix_core_sentence_charge', 'sentence', ['charge_id'], unique=False, schema='core')
    op.create_index('ix_core_sentence_party_type', 'sentence', ['case_party_id', 'sentence_type'], unique=False, schema='core')
    op.create_index('ix_core_sentence_snapshot', 'sentence', ['published_snapshot_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_core_sentence_snapshot', table_name='sentence', schema='core')
    op.drop_index('ix_core_sentence_party_type', table_name='sentence', schema='core')
    op.drop_index('ix_core_sentence_charge', table_name='sentence', schema='core')
    op.drop_table('sentence', schema='core')
    op.drop_index('ix_core_charge_snapshot', table_name='charge', schema='core')
    op.drop_index('ix_core_charge_party', table_name='charge', schema='core')
    op.drop_table('charge', schema='core')
    op.drop_index(op.f('ix_forms_generated_document_generation_request_id'), table_name='generated_document', schema='forms')
    op.drop_index(op.f('ix_forms_generated_document_created_by_user_id'), table_name='generated_document', schema='forms')
    op.drop_index(op.f('ix_forms_generated_document_artifact_id'), table_name='generated_document', schema='forms')
    op.drop_table('generated_document', schema='forms')
    op.drop_index('ix_core_judgment_snapshot', table_name='judgment', schema='core')
    op.drop_index('ix_core_judgment_case_date', table_name='judgment', schema='core')
    op.drop_table('judgment', schema='core')
    op.drop_index('ix_core_case_party_snapshot_role', table_name='case_party', schema='core')
    op.drop_index('ix_core_case_party_person', table_name='case_party', schema='core')
    op.drop_table('case_party', schema='core')
    op.drop_index('ix_core_address_snapshot', table_name='address', schema='core')
    op.drop_index('ix_core_address_admin', table_name='address', schema='core')
    op.drop_table('address', schema='core')
    op.drop_index('ix_review_review_comment_field', table_name='review_comment', schema='review')
    op.drop_index('ix_review_review_comment_author', table_name='review_comment', schema='review')
    op.drop_table('review_comment', schema='review')
    op.drop_index('ix_review_field_correction_version', table_name='field_correction', schema='review')
    op.drop_index('ix_review_field_correction_actor', table_name='field_correction', schema='review')
    op.drop_table('field_correction', schema='review')
    op.drop_index('ix_forms_form_generation_request_status', table_name='form_generation_request', schema='forms')
    op.drop_index(op.f('ix_forms_form_generation_request_requested_by_user_id'), table_name='form_generation_request', schema='forms')
    op.drop_index(op.f('ix_forms_form_generation_request_published_snapshot_id'), table_name='form_generation_request', schema='forms')
    op.drop_index(op.f('ix_forms_form_generation_request_form_definition_id'), table_name='form_generation_request', schema='forms')
    op.drop_index(op.f('ix_forms_form_generation_request_approved_review_version_id'), table_name='form_generation_request', schema='forms')
    op.drop_table('form_generation_request', schema='forms')
    op.drop_index('ix_core_source_document_link_entity', table_name='source_document_link', schema='core')
    op.drop_index('ix_core_source_document_link_document', table_name='source_document_link', schema='core')
    op.drop_table('source_document_link', schema='core')
    op.drop_index('ix_core_person_snapshot_name', table_name='person', schema='core')
    op.drop_table('person', schema='core')
    op.drop_index('ix_core_court_case_snapshot_status', table_name='court_case', schema='core')
    op.drop_index('ix_core_court_case_court', table_name='court_case', schema='core')
    op.drop_table('court_case', schema='core')
    op.drop_index('ix_review_field_review_status', table_name='field_review', schema='review')
    op.drop_index('ix_review_field_review_reviewer', table_name='field_review', schema='review')
    op.drop_index('ix_review_field_review_machine_field', table_name='field_review', schema='review')
    op.drop_table('field_review', schema='review')
    op.drop_index('ix_processing_extraction_warning_snapshot_severity', table_name='extraction_warning', schema='processing')
    op.drop_index('ix_processing_extraction_warning_field_status', table_name='extraction_warning', schema='processing')
    op.drop_table('extraction_warning', schema='processing')
    op.drop_index('ix_processing_evidence_ref_page', table_name='evidence_ref', schema='processing')
    op.drop_index('ix_processing_evidence_ref_field_status', table_name='evidence_ref', schema='processing')
    op.drop_table('evidence_ref', schema='processing')
    op.drop_index('ix_core_published_snapshot_status_time', table_name='published_snapshot', schema='core')
    op.drop_table('published_snapshot', schema='core')
    op.drop_index('ix_review_approval_decision', table_name='approval', schema='review')
    op.drop_index('ix_review_approval_actor', table_name='approval', schema='review')
    op.drop_table('approval', schema='review')
    op.drop_index('ix_processing_extracted_field_entity_status', table_name='extracted_field', schema='processing')
    op.drop_table('extracted_field', schema='processing')
    op.drop_index('ix_review_review_version_supersedes', table_name='review_version', schema='review')
    op.drop_index('ix_review_review_version_status_locked', table_name='review_version', schema='review')
    op.drop_index('ix_review_review_version_extraction_snapshot', table_name='review_version', schema='review')
    op.drop_table('review_version', schema='review')
    op.drop_index('ix_processing_extracted_entity_snapshot_status', table_name='extracted_entity', schema='processing')
    op.drop_table('extracted_entity', schema='processing')
    op.drop_index('ix_processing_extraction_snapshot_run_status', table_name='extraction_snapshot', schema='processing')
    op.drop_index('ix_processing_extraction_snapshot_document_created_at', table_name='extraction_snapshot', schema='processing')
    op.drop_table('extraction_snapshot', schema='processing')
    op.drop_index(op.f('ix_forms_form_field_mapping_field_definition_id'), table_name='form_field_mapping', schema='forms')
    op.drop_table('form_field_mapping', schema='forms')
    op.drop_index('ix_processing_pipeline_step_status_created_at', table_name='pipeline_step', schema='processing')
    op.drop_index('ix_processing_pipeline_step_run_status', table_name='pipeline_step', schema='processing')
    op.drop_table('pipeline_step', schema='processing')
    op.drop_index(op.f('ix_forms_form_field_definition_form_definition_id'), table_name='form_field_definition', schema='forms')
    op.drop_table('form_field_definition', schema='forms')
    op.drop_index('ix_processing_run_status_created_at', table_name='processing_run', schema='processing')
    op.drop_index('ix_processing_run_job_created_at', table_name='processing_run', schema='processing')
    op.drop_index('ix_processing_run_document_status', table_name='processing_run', schema='processing')
    op.drop_table('processing_run', schema='processing')
    op.drop_index('ix_ingest_document_page_version_status', table_name='document_page', schema='ingest')
    op.drop_table('document_page', schema='ingest')
    op.drop_index(op.f('ix_forms_form_definition_template_version_id'), table_name='form_definition', schema='forms')
    op.drop_index(op.f('ix_forms_form_definition_catalog_entry_id'), table_name='form_definition', schema='forms')
    op.drop_table('form_definition', schema='forms')
    op.drop_index('ix_ingest_document_version_document_status', table_name='document_version', schema='ingest')
    op.drop_table('document_version', schema='ingest')
    op.drop_index(op.f('ix_forms_form_template_version_template_id'), table_name='form_template_version', schema='forms')
    op.drop_index(op.f('ix_forms_form_template_version_artifact_id'), table_name='form_template_version', schema='forms')
    op.drop_table('form_template_version', schema='forms')
    op.drop_index('ix_ingest_artifact_type_created_at', table_name='artifact', schema='ingest')
    op.drop_index('ix_ingest_artifact_job_document', table_name='artifact', schema='ingest')
    op.drop_index('ix_ingest_artifact_checksum', table_name='artifact', schema='ingest')
    op.drop_table('artifact', schema='ingest')
    op.drop_index('ix_ingest_document_status_created_at', table_name='document', schema='ingest')
    op.drop_index('ix_ingest_document_job_status', table_name='document', schema='ingest')
    op.drop_table('document', schema='ingest')
    op.drop_index('ix_review_review_task_status_priority', table_name='review_task', schema='review')
    op.drop_index('ix_review_review_task_assignee_status', table_name='review_task', schema='review')
    op.drop_table('review_task', schema='review')
    op.drop_index('ix_ingest_job_status_created_at', table_name='job', schema='ingest')
    op.drop_index('ix_ingest_job_requested_by_created_at', table_name='job', schema='ingest')
    op.drop_table('job', schema='ingest')
    op.drop_index(op.f('ix_forms_form_template_catalog_entry_id'), table_name='form_template', schema='forms')
    op.drop_table('form_template', schema='forms')
    op.drop_index(op.f('ix_audit_audit_event_subject_id'), table_name='audit_event', schema='audit')
    op.drop_index('ix_audit_audit_event_subject', table_name='audit_event', schema='audit')
    op.drop_index(op.f('ix_audit_audit_event_event_type'), table_name='audit_event', schema='audit')
    op.drop_index('ix_audit_audit_event_correlation', table_name='audit_event', schema='audit')
    op.drop_index(op.f('ix_audit_audit_event_actor_user_id'), table_name='audit_event', schema='audit')
    op.drop_table('audit_event', schema='audit')
    op.drop_index('ix_audit_app_user_role_user_status', table_name='app_user_role', schema='audit')
    op.drop_index('ix_audit_app_user_role_role_status', table_name='app_user_role', schema='audit')
    op.drop_table('app_user_role', schema='audit')
    op.drop_index('ix_forms_form_catalog_entry_domain_status', table_name='form_catalog_entry', schema='forms')
    op.drop_table('form_catalog_entry', schema='forms')
    op.drop_index('ix_audit_app_user_status', table_name='app_user', schema='audit')
    op.drop_table('app_user', schema='audit')
    op.drop_index('ix_audit_access_role_status', table_name='access_role', schema='audit')
    op.drop_table('access_role', schema='audit')
    # ### end Alembic commands ###
